version: '3.7'

services:
  compiler:
    image: wingzzz2003/codeserver_ubuntu:beta
    volumes:
      - ${PWD}/4.5.0/.config/code-server/config.yaml:/root/.config/code-server/config.yaml
      - ${PWD}/4.5.0/.local/share/code-server/User/settings.json:/root/.local/share/code-server/User/settings.json
    ports:
      - 8080:8080
    entrypoint: code-server
